sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t everoad/react-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true everoad/react-docker-app npm run test -- --coverage

after_success:
  - echo "Test Success"