version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/web/node_modules
      - ./:/app/web
    stdin_open: true
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/web/node_modules
      - ./:/app/web
    command: ["npm", "run", "test"]
  